version: "3"

services:
  frontend:
    container_name: meu_app_front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    ports:
      - 8080:8080

  backend:
    container_name: meu_app_back
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
  #   depends_on:
  #     - db
  #   environment:
  #     DB_USER: root
  #     DB_PASSWORD: password
  #     DB_HOST: db
  #     DB_PORT: 3306
  #     DB_NAME: meu_app
  #     JWT_SECRET: secret

  # db:
  #   container_name: meu_app_db
  #   image: mysql:8.0.32
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password